(()=>{var __webpack_modules__={"./src/js/_components.js":
/*!*******************************!*\
  !*** ./src/js/_components.js ***!
  \*******************************/(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _components_func_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./components/func.js */ "./src/js/components/func.js");\n/* harmony import */ var _components_func_js__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_components_func_js__WEBPACK_IMPORTED_MODULE_0__);\n// Подключаем созданные файлы в папке components\n\n\n//# sourceURL=webpack://max-gulp/./src/js/_components.js?')},"./src/js/_vars.js":
/*!*************************!*\
  !*** ./src/js/_vars.js ***!
  \*************************/(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony export */ __webpack_require__.d(__webpack_exports__, {\n/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)\n/* harmony export */ });\n/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ({\n  windowEl: window,\n  documentEl: document,\n  htmlEl: document.documentElement,\n  bodyEl: document.body,\n  select: document.querySelector,\n  selectAll: document.querySelectorAll\n});\n\n//# sourceURL=webpack://max-gulp/./src/js/_vars.js?')},"./src/js/components/func.js":
/*!***********************************!*\
  !*** ./src/js/components/func.js ***!
  \***********************************/()=>{eval("// Пример создания функции для экспорта\n// export const asd = () => {\n// console.log('Hello');\n// }\n\n//# sourceURL=webpack://max-gulp/./src/js/components/func.js?")},"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/(__unused_webpack_module,__webpack_exports__,__webpack_require__)=>{"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _vars__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./_vars */ "./src/js/_vars.js");\n/* harmony import */ var _components__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./_components */ "./src/js/_components.js");\n\n\n\n//# sourceURL=webpack://max-gulp/./src/js/main.js?')}},__webpack_module_cache__={};function __webpack_require__(_){var e=__webpack_module_cache__[_];if(void 0!==e)return e.exports;var r=__webpack_module_cache__[_]={exports:{}};return __webpack_modules__[_](r,r.exports,__webpack_require__),r.exports}__webpack_require__.n=_=>{var e=_&&_.__esModule?()=>_.default:()=>_;return __webpack_require__.d(e,{a:e}),e},__webpack_require__.d=(_,e)=>{for(var r in e)__webpack_require__.o(e,r)&&!__webpack_require__.o(_,r)&&Object.defineProperty(_,r,{enumerable:!0,get:e[r]})},__webpack_require__.o=(_,e)=>Object.prototype.hasOwnProperty.call(_,e),__webpack_require__.r=_=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(_,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(_,"__esModule",{value:!0})};var __webpack_exports__=__webpack_require__("./src/js/main.js")})();
//# sourceMappingURL=main.js.map
